from typing import List
from pydantic import BaseSettings
import os


class MLConfig(BaseSettings):
    model_path: str = os.path.join(os.path.dirname(__file__), "models/e25.h5")

    classes: List[str] = [
        "Smiley Face",
        "Alarm Clock",
        "Donut",
        "Butterfly",
        "Hat",
        "Wristwatch",
        "Paper Clip",
        "Rainbow",
        "Microphone",
        "Screwdriver",
        "Chair",
        "Spoon",
        "Snake",
        "Cloud",
        "Scissors",
        "Eye",
        "Bridge",
        "Suitcase",
        "Light Bulb",
        "Mushroom",
        "Book",
        "Dumbbell",
        "Flower",
        "Laptop",
        "Ice Cream",
        "Lightning",
        "Sword",
        "Tree",
        "Headphones",
        "Moon",
        "Baseball Bat",
        "Ceiling Fan",
        "Sun",
        "Bed",
        "Cup",
        "Table",
        "Hammer",
        "Pants",
        "Lollipop",
        "Ladder",
        "Tennis Racquet",
        "Cat",
        "Car",
        "Fan",
        "T-shirt",
        "Umbrella",
        "Bench",
        "Airplane",
        "Envelope",
        "Coffee Cup",
        "Hot Dog",
        "Pizza",
        "Cell Phone",
        "Radio",
        "Baseball",
        "Camera",
        "Bird",
        "Star",
        "Spider",
        "Pencil",
        "Key",
        "Mountain",
        "Circle",
        "Cookie",
        "Candle",
        "Sock",
        "Triangle",
        "Basketball",
        "Knife",
        "Apple",
        "Clock",
    ]

    all_classes: List[str] = [
        "Saw",
        "Coffee Cup",
        "Power Outlet",
        "Microphone",
        "Triangle",
        "Cat",
        "Paper Clip",
        "Drums",
        "Diving Board",
        "Sun",
        "Scissors",
        "Butterfly",
        "Ladder",
        "Beard",
        "Helmet",
        "Bicycle",
        "Face",
        "Eye",
        "Syringe",
        "Bed",
        "Smiley Face",
        "Sword",
        "Door",
        "Spider",
        "Bridge",
        "Spoon",
        "Fan",
        "Cell Phone",
        "Donut",
        "Rifle",
        "Baseball Bat",
        "Camera",
        "Baseball",
        "Screwdriver",
        "Table",
        "Anvil",
        "Frying_pan",
        "Tree",
        "Chair",
        "Tooth",
        "Rainbow",
        "Bench",
        "Star",
        "Ceiling Fan",
        "Headphones",
        "Moon",
        "Key",
        "Eyeglasses",
        "Lollipop",
        "Cookie",
        "Hat",
        "Shorts",
        "Grapes",
        "Pencil",
        "Hot Dog",
        "Bird",
        "Basketball",
        "Hammer",
        "Radio",
        "T-shirt",
        "Pizza",
        "Shovel",
        "Flower",
        "Clock",
        "Wristwatch",
        "Tent",
        "Ice Cream",
        "Airplane",
        "Mushroom",
        "Wheel",
        "Bread",
        "Mountain",
        "Axe",
        "Stop Sign",
        "Lightning",
        "Car",
        "Laptop",
        "Snake",
        "Dumbbell",
        "Sock",
        "Cup",
        "Moustache",
        "Book",
        "Traffic Light",
        "Umbrella",
        "Line",
        "Suitcase",
        "Circle",
        "Candle",
        "Pants",
        "Tennis_racquet",
        "Alarm Clock",
        "Square",
        "Pillow",
        "Cloud",
        "Broom",
        "Knife",
        "Light Bulb",
        "Apple",
        "Envelope",
    ]
