from typing import List
import os


class MLConfig:
    model_path: str = os.path.join(os.path.dirname(__file__), "models/e25.h5")

    classes: List[str] = [
        "Smiley Face",
        "Alarm Clock",
        "Donut",
        "Butterfly",
        "Hat",
        "Wristwatch",
        "Paper Clip",
        "Rainbow",
        "Microphone",
        "Screwdriver",
        "Chair",
        "Spoon",
        "Snake",
        "Cloud",
        "Scissors",
        "Eye",
        "Bridge",
        "Suitcase",
        "Light Bulb",
        "Mushroom",
        "Book",
        "Dumbbell",
        "Flower",
        "Laptop",
        "Ice Cream",
        "Lightning",
        "Sword",
        "Tree",
        "Headphones",
        "Moon",
        "Baseball Bat",
        "Ceiling Fan",
        "Sun",
        "Bed",
        "Cup",
        "Table",
        "Hammer",
        "Pants",
        "Lollipop",
        "Ladder",
        "Tennis Racquet",
        "Cat",
        "Car",
        "Fan",
        "T-shirt",
        "Umbrella",
        "Bench",
        "Airplane",
        "Envelope",
        "Coffee Cup",
        "Hot Dog",
        "Pizza",
        "Cell Phone",
        "Radio",
        "Baseball",
        "Camera",
        "Bird",
        "Star",
        "Spider",
        "Pencil",
        "Key",
        "Mountain",
        "Circle",
        "Cookie",
        "Candle",
        "Sock",
        "Triangle",
        "Basketball",
        "Knife",
        "Apple",
        "Clock",
    ]
